### ISSUE TITLE
get_financial_statementsにpaginationを実装

### ISSUE THREAD

**Issue by h-wakaba** [J-Quants/JQuantsR#30]
現在はpaginationを実装できていないので、実装する

**Comment by h-wakaba** [comment]
get_financial_statements以外にもpaginationがある

対応案：get_from_apiの中で対応する
- まずpaginationを与えずにAPIを叩く
- names(httr::content(httr::GET(...)))にpagination_keyがあれば、それをクエリストリングに与えて、pagination_keyがなくなるまで繰り返す。なければ終了。これをwhileループの中で繰り返す

**Comment by JQUANTSR** [comment]
いつも楽しく使わせて頂いてます。
上記の実装はいつ頃になりそうでしょうか？
楽しみにしてます！

**Comment by h-wakaba** [comment]
@JQUANTSR 
ご利用いただきありがとうございます！
遅くなりましたが対応いたしました。アップデートいただけますと幸いです。

**Comment by JQUANTSR** [comment]
アップデートしてうまくダウンロード出来るようになりました！　ありがとうございました！！
